app = "spring-boot-app"  # change this to your Fly.io app name

primary_region = "cdg"   # e.g. Paris, close to Egypt

[build]
dockerfile = "src/backend/spring/Dockerfile"

[env]
JAVA_OPTS = "-Xms128m -Xmx256m"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
